// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://akgmvwevnljjhcjgnzly.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFrZ212d2V2bmxqamhjamduemx5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0Mjg3MzksImV4cCI6MjA2NDAwNDczOX0.Ylo3whNT5cRQlLEe9ZtwIALI_-2FtnTGBk__9jyuPFQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);